# Generated by Django 5.0 on 2023-12-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('aadhar_number', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('upi_details', models.CharField(max_length=255)),
                ('local_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('field_experience', models.CharField(max_length=255)),
                ('services_provided', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
